/**
 * Marker vocabulary shared by every binary parser.
 *
 * Two separate questions are asked of any metadata blob:
 *
 *   1. Does it carry AI provenance? (C2PA manifests, `digitalSourceType`,
 *      vendor names in a generator field.)
 *   2. Does it carry *you*? (GPS coordinates, a camera serial number, your
 *      name in an Artist tag, the exact second you pressed the shutter.)
 *
 * The second question is the one that matters most often, and it is the one
 * most provenance tooling ignores entirely.
 */

import { decodeAsciiLoose } from './util/text-codec.js';
import type { Confidence, PrivacyFindings } from './types.js';

/** Structures that indicate a C2PA / JUMBF content-credentials container. */
export const C2PA_MARKERS: readonly string[] = [
  'c2pa',
  'jumb',
  'c2ma',
  'contentcredentials',
  'contentauth',
  'cai:',
];

/** Strings that suggest AI provenance without proving a manifest exists. */
export const AI_MARKERS: readonly string[] = [
  'c2pa',
  'contentcredentials',
  'digitalsourcetype',
  'trainedalgorithmicmedia',
  'compositewithtrainedalgorithmicmedia',
  'algorithmicmedia',
  'aigc',
  'ai generated',
  'ai-generated',
  'generated by',
  'synthid',
  'midjourney',
  'stable diffusion',
  'dall-e',
  'firefly',
  'dcterms:provenance',
];

/**
 * Markers whose presence is a parsed provenance claim rather than a hint.
 *
 * Finding one of these in a metadata structure is `confirmed`; finding an
 * entry from `AI_MARKERS` is only `probable`.
 */
export const PROVENANCE_CLAIM_MARKERS: readonly string[] = [
  'digitalsourcetype',
  'trainedalgorithmicmedia',
  'compositewithtrainedalgorithmicmedia',
  'c2pa',
  'contentcredentials',
];

/** Substrings that mean "this metadata says where you were". */
const LOCATION_MARKERS: readonly string[] = [
  'gpslatitude',
  'gpslongitude',
  'gpsposition',
  'gpscoordinates',
  'gpsaltitude',
  'geo:lat',
  'exif:gps',
  '<gps',
];

/** Substrings that identify the device that produced the file. */
const DEVICE_MARKERS: readonly string[] = [
  'serialnumber',
  'bodyserialnumber',
  'lensserialnumber',
  'internalserialnumber',
  'cameraserial',
  'tiff:make',
  'tiff:model',
  'exif:lensmodel',
  'hostcomputer',
];

/** Substrings that name a human. */
const AUTHOR_MARKERS: readonly string[] = [
  'dc:creator',
  'xmp:creatortool',
  'photoshop:credit',
  'photoshop:author',
  'iptc:by-line',
  'artist',
  'ownername',
  'copyright',
  'rights',
  'lastmodifiedby',
];

/** Substrings that pin the file to a moment. */
const TIMESTAMP_MARKERS: readonly string[] = [
  'datetimeoriginal',
  'createdate',
  'modifydate',
  'xmp:createdate',
  'xmp:modifydate',
  'dcterms:created',
  'gpsdatestamp',
];

/** Lowercased ASCII projection of a blob, for case-insensitive substring search. */
export function asciiView(blob: Uint8Array, limit = blob.length): string {
  const slice = limit < blob.length ? blob.subarray(0, limit) : blob;
  return decodeAsciiLoose(slice).toLowerCase();
}

/** Which of `needles` appear in an already-lowercased ASCII view. */
export function findIn(view: string, needles: readonly string[]): string[] {
  const hits: string[] = [];
  for (const n of needles) {
    if (view.includes(n)) hits.push(n);
  }
  return hits;
}

/** How strongly a set of marker hits implies AI provenance. */
export function markerConfidence(hits: readonly string[]): Confidence {
  return hits.some((h) => PROVENANCE_CLAIM_MARKERS.includes(h)) ? 'confirmed' : 'probable';
}

/** Scan a metadata blob for identifying (non-provenance) information. */
export function scanPrivacy(view: string): PrivacyFindings {
  return {
    hasLocation: LOCATION_MARKERS.some((m) => view.includes(m)),
    hasDeviceIdentity: DEVICE_MARKERS.some((m) => view.includes(m)),
    hasAuthorIdentity: AUTHOR_MARKERS.some((m) => view.includes(m)),
    hasTimestamps: TIMESTAMP_MARKERS.some((m) => view.includes(m)),
  };
}

/** Union of two privacy scans. */
export function mergePrivacy(a: PrivacyFindings, b: PrivacyFindings): PrivacyFindings {
  return {
    hasLocation: a.hasLocation || b.hasLocation,
    hasDeviceIdentity: a.hasDeviceIdentity || b.hasDeviceIdentity,
    hasAuthorIdentity: a.hasAuthorIdentity || b.hasAuthorIdentity,
    hasTimestamps: a.hasTimestamps || b.hasTimestamps,
  };
}

/** True when any identifying category was found. */
export function hasAnyPrivacyRisk(p: PrivacyFindings): boolean {
  return p.hasLocation || p.hasDeviceIdentity || p.hasAuthorIdentity || p.hasTimestamps;
}

/** Human summary of a privacy scan, for report output. */
export function describePrivacy(p: PrivacyFindings): string[] {
  const out: string[] = [];
  if (p.hasLocation) out.push('location (GPS coordinates)');
  if (p.hasDeviceIdentity) out.push('device identity (make, model or serial number)');
  if (p.hasAuthorIdentity) out.push('author identity (creator, artist or copyright)');
  if (p.hasTimestamps) out.push('capture or edit timestamps');
  return out;
}
